name: 'Git Version'
description: 'Bash script to perform basic automated sematic versioning based on git tags'
inputs:
  component:
    description: 'Name of an option sub-component, used as prefix for the git tags'
    required: false
    default: ''
  paths:
    description: 'Paths that contain changes to consider for git messages'
    required: false
    default: ''
  major_bump_message:
    description: 'String to look for in commit messages to trigger a major bump'
    required: false
    default: ''
  minor_bump_message:
    description: 'String to look for in commit messages to trigger a minor bump'
    required: false
    default: ''
  poc_release_branch_prefix:
    description: 'Prefix for the branch name to use for PoC releases'
    required: false
    default: ''
outputs:
  number_of_changes_since_last_tag:
    description: "The number of commits since the last tag"
    value: ${{ steps.version.outputs.number_of_changes_since_last_tag }}
  previous_version:
    description: "The previous version number"
    value: ${{ steps.version.outputs.previous_version }}
  new_version:
    description: "The new version number"
    value: ${{ steps.version.outputs.new_version }}
runs:
  using: "composite"
  steps:
    - name: Run version.sh
      uses: "docker://alpine/git:2.45.2"
      id: version
      env:
        COMPONENT: ${{ inputs.component }}
        PATHS: ${{ inputs.paths }}
        MAJOR_BUMP_MESSAGE: ${{ inputs.major_bump_message }}
        MINOR_BUMP_MESSAGE: ${{ inputs.minor_bump_message }}
        POC_RELEASE_BRANCH_PREFIX: ${{ inputs.poc_release_branch_prefix }}
      with:
        entrypoint: /bin/sh -c
        args: $GITHUB_ACTION_PATH/version.sh >> $GITHUB_OUTPUT
