name: Release new version of the action
run-name: ${{ github.actor }} is releasing a new version
on:
  push:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bats/bats:latest
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git
        run: apk add --no-cache git

      - name: Run tests
        run: bats tests

      - name: Use the action
        uses: ./../action.yml

  release:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get next version
        uses: ./../action.yml
        id: version

      - name: Create tag
        if: ${{ steps.version.outputs.number_of_changes_since_last_tag != '0' }}
        uses: actions/github-script@v5
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version.outputs.next_version }}',
              sha: context.sha
            })
