name: Test a new version
run-name: ${{ github.actor }} is testing a new version
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: build test-runner
        run: docker build -t test-runner tests

      - name: Run tests
        uses: docker://test-runner
        with:
          args: tests

      - name: Use the action
        id: version
        uses: ./
      
      - name: Check output
        run: |-
          if [ -z "${{ steps.version.outputs.new_version }}" ]; then 
            echo "Output is missing";
            exit 1;
          fi