name: Test a new version
run-name: ${{ github.actor }} is testing a new version
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: |-
          docker build -t test-runner tests
          docker run --rm -v $(pwd):/project -w /project --user 1001 test-runner /project/tests

      - name: Use the action
        id: version
        uses: ./
      
      - name: Check output
        run: |-
          if [ -z "${{ steps.version.outputs.number_of_changes_since_last_tag }}" ]; then 
            echo "Number output is missing";
            exit 1;
          fi
          if [ -z "${{ steps.version.outputs.previous_version }}" ]; then 
            echo "Previous uutput is missing";
            exit 1;
          fi
          if [ -z "${{ steps.version.outputs.new_version }}" ]; then 
            echo "New output is missing";
            exit 1;
          fi