name: Test a new version
run-name: ${{ github.actor }} is testing a new version
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: bats/bats:latest
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install git
        run: apk add --no-cache git

      - name: Run tests
        run: bats tests

      - name: Use the action
        uses: ./../action.yml