name: Test a new version
run-name: ${{ github.actor }} is testing a new version
on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run tests
        run: docker run -it -v $(pwd):/project bats/bats:latest /project/tests
